# Generated by Django 2.2.7 on 2019-11-29 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='owner',
        ),
    ]
