# Generated by Django 2.2.7 on 2019-11-29 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20191129_2136'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commet',
            new_name='Comment',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='commets',
            new_name='comments',
        ),
    ]
